// tailwind.config.js
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";
import aspectRatio from "@tailwindcss/aspect-ratio";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#4c6455",
        "on-tertiary-fixed-variant": "#3e4a40",
        "surface-variant": "#e3e2e0",
        "tertiary-container": "#99a69a",
        background: "#faf9f7",
        "surface-tint": "#4c6455",
        "inverse-primary": "#b2cdbb",
        "on-background": "#1a1c1b",
        secondary: "#795555",
        outline: "#727973",
        surface: "#faf9f7",
        "error-container": "#ffdad6",
        "surface-container": "#efeeec",
        "on-secondary-fixed-variant": "#5f3e3f",
        "on-error-container": "#93000a",
        "on-surface-variant": "#424844",
        "surface-container-low": "#f4f3f1",
        "inverse-on-surface": "#f1f1ef",
        "on-tertiary-fixed": "#131e16",
        "on-primary-container": "#273e31",
        "on-error": "#ffffff",
        "primary-fixed": "#cee9d6",
        "on-secondary-fixed": "#2e1415",
        "tertiary-fixed": "#d9e6d9",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#b2cdbb",
        "surface-container-highest": "#e3e2e0",
        "on-primary-fixed-variant": "#344c3e",
        "on-surface": "#1a1c1b",
        "outline-variant": "#c2c8c2",
        "surface-bright": "#faf9f7",
        "secondary-fixed": "#ffdad9",
        "on-primary-fixed": "#082014",
        "primary-container": "#8fa998",
        "surface-container-high": "#e9e8e6",
        "inverse-surface": "#2f3130",
        "on-tertiary-container": "#303c33",
        error: "#ba1a1a",
        tertiary: "#556157",
        "secondary-fixed-dim": "#eabbbb",
        "tertiary-fixed-dim": "#bdcabd",
        "secondary-container": "#fbcccc",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-dim": "#dadad8",
        "on-secondary-container": "#785454",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Manrope"],
        label: ["Manrope"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [forms(), containerQueries(), aspectRatio()],
};
